config/routes.rb
Rails.application.routes.draw do

  get 'puntuaciones/index'

  devise_for :usuarios, :controllers => {
    :sessions => 'usuario/sessions',
    :registrations => 'usuario/registrations',
    :passwords => 'usuario/password'
    }

  post 'registrar' => 'servicio/usuarios#registrar'
  post 'login' => 'servicio/usuarios#login'

  post 'juegos/registrar' => 'servicio/juegos#registrar'
  post 'juegos/comprobar' => 'servicio/juegos#comprobar_nombre'

  post 'puntuaciones/registrar' => 'servicio/puntuaciones#registrar'
  post 'puntuaciones/mejores' => 'servicio/puntuaciones#mejores'

  root 'inicio#inicio'
  
  get 'mis-juegos' => 'juegos#mis_juegos'
  
  get 'juegos' => 'juegos#index'
  get 'buscar' => 'juegos#buscar'
  
  get 'puntuaciones/:juego_id' => 'puntuaciones#index', :as => 'puntuaciones_juego'
  
  get 'puntuaciones/niveles/:puntuacion_id' => 'niveles#index', :as => 'puntuaciones_por_nivel'

  devise_scope :usuario do
   get "mi-cuenta", to: "devise/passwords#edit"
  end

end

app/controllers/puntuaciones_controller.rb
class PuntuacionesController < ApplicationController
  
    before_filter :authenticate_usuario!

  
  ##
  # Permite obtener todas las puntuaciones asociadas a un juego
  #
  # * <tt>juego_id</tt> - Id del juego para realizar la búsqueda.
  
  def index
    juego_id = params.require(:juego_id)
    @juego = Juego.find juego_id
    @puntuaciones = Puntuacion.por_juego juego_id
  end
end

app/controllers/servicio/puntuaciones_controller.rb
class Servicio::PuntuacionesController < Servicio::ServicioController
  
  around_filter :comprobar_token_acceso_filter
  
  def registrar
  
    puntuacion = Puntuacion.new params.permit(:puntos)
    puntuacion.usuario = token_acceso.usuario
    puntuacion.juego = token_acceso.juego
    
    params.require(:niveles).each do |nivel|
      puntuacion.niveles << Nivel.new(nivel.permit(:numero, :puntos))
    end
    
    puntuacion.save
  
    render :json => {
      :mensaje => 'Puntuación registrada',
      :errores => {}
    }
    
  end
  
  def mejores
    
    pagina = params.fetch('pagina', 0)
    
    mejores = []
    Puntuacion.mejores(pagina).each do |puntuacion|
      mejores << {
        :puntos => puntuacion.puntos,
        :nombre => puntuacion.usuario.nombre
      }
    end
    
    render :json => {
      :mensaje => 'Puntuaciones obtenidas',
      :info => mejores,
      :errores => {}
    }
    
  end
end

app/views/puntuaciones/index.html.erb
<% content_for :opcion, 'juegos' %>
<% content_for :titulo do %>
	Puntuaciones de <%= @juego.nombre %>
<% end %>
<% content_for :subtitulo do %>
	Aquí se mostrarán todas las puntuaciones obtenidas en el juego <%= @juego.nombre %>
<% end %>

<% if !request.referer.nil? && request.referer.end_with?('mis-juegos') %>
	<ol class="breadcrumb">
	  <li><%= link_to 'Mis Juegos', mis_juegos_path %></li>
	  <li class="active">Puntuaciones en <%= @juego.nombre %></li>
	</ol>
<% else %>
	<ol class="breadcrumb">
	  <li><%= link_to 'Juegos', root_path %></li>
	  <li class="active">Puntuaciones en <%= @juego.nombre %></li>
	</ol>
<% end %>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>Usuario</th>
			<th>Puntuación</th>		
		</tr>
	</thead>
	<tbody>
		<% @puntuaciones.each do |puntuacion| %>
			<tr>
				<td>
					<%= link_to puntuacion.usuario.nombre, puntuaciones_por_nivel_path(puntuacion.id) %>	
				</td>
				<td>
					<%= puntuacion.puntos %>
				</td>
			</tr>
		<% end %>
	</tbody>