config/routes.rb
Rails.application.routes.draw do

  get 'puntuaciones/index'

  devise_for :usuarios, :controllers => {
    :sessions => 'usuario/sessions',
    :registrations => 'usuario/registrations',
    :passwords => 'usuario/password'
    }

  post 'registrar' => 'servicio/usuarios#registrar'
  post 'login' => 'servicio/usuarios#login'

  post 'juegos/registrar' => 'servicio/juegos#registrar'
  post 'juegos/comprobar' => 'servicio/juegos#comprobar_nombre'

  post 'puntuaciones/registrar' => 'servicio/puntuaciones#registrar'
  post 'puntuaciones/mejores' => 'servicio/puntuaciones#mejores'

  root 'inicio#inicio'
  
  get 'mis-juegos' => 'juegos#mis_juegos'
  
  get 'juegos' => 'juegos#index'
  get 'buscar' => 'juegos#buscar'
  
  get 'puntuaciones/:juego_id' => 'puntuaciones#index', :as => 'puntuaciones_juego'
  
  get 'puntuaciones/niveles/:puntuacion_id' => 'niveles#index', :as => 'puntuaciones_por_nivel'

  devise_scope :usuario do
   get "mi-cuenta", to: "devise/passwords#edit"
  end

end

app/models/juego.rb
class Juego < ActiveRecord::Base
  
  JUEGOS_POR_PAGINA = 10
  
  has_many :token_accesos
  has_many :puntuaciones

  validates :nombre, uniqueness: true
  
  ##
  # Permite obtener todos los juegos por orden de popularidad y paginados.
  # 
  # * <tt>numero</tt> - Número de página a mostrar. Si no se incluye de muestra la primera.
  
  scope :pagina_todos, ->(numero) {
    order(:jugadores => :desc)
    .limit(JUEGOS_POR_PAGINA)
    .offset((numero - 1) * JUEGOS_POR_PAGINA)
  }
  
  ##
  # Permite obtener los juegos por el id del usuario.
  #
  # * <tt>usuario</tt> - Usuario para buscar sus juegos asociados.
  
  scope :por_usuario, ->(usuario) {
    joins(:token_accesos)
    .merge(TokenAcceso.where(:usuario_id => usuario.id))
  }
  
  ##
  # Permite obtener una página con los juegos de un usuario ordenados alfabéticamente. 
  # 
  # * <tt>usuario</tt> - Usuario para buscar sus juegos asociados.
  # * <tt>numero</tt> - Número de página a mostrar. Si no se incluye se muestra la primera.
  
  scope :pagina_por_usuario, ->(usuario, numero) {
    por_usuario(usuario)
    .order(:nombre => :asc)
    .limit(JUEGOS_POR_PAGINA)
    .offset((numero - 1) * JUEGOS_POR_PAGINA)
  }
  
  ##
  # Permite buscar todos los juegos que contengan una cadena.
  #
  # * <tt>nombre</tt> - Nombre por el que se realiza la búsqueda. 
  
  scope :buscar, ->(nombre) {
    where('nombre LIKE ?', '%' + nombre + '%')
  }
  
  ##
  # Permite obtener una página con los juegos que contengan el nombre buscado.
  # Se mostrarán por orden de popularidad.
  #
  # * <tt>numero</tt> - Número de página a mostrar. Si no se incluye se muestra la primera.
  # * <tt>nombre</tt> - Nombre por el que se realiza la búsqueda.
  
  scope :pagina_buscar, ->(numero, nombre) {
    buscar(nombre)
    .order(:jugadores => :desc)
    .limit(JUEGOS_POR_PAGINA)
    .offset((numero - 1) * JUEGOS_POR_PAGINA)
  }

  ##
  # Permite obtener el número de páginas totales.

  def self.paginas_todos
    ((count - 1) / JUEGOS_POR_PAGINA) + 1
  end

  ## 
  # Permite obtener el número de páginas totales al realizar una búsqueda.
  #
  # * <tt>nombre</tt> - Nombre por el que se realiza la búsqueda.
  
  def self.paginas_buscar(nombre)
    ((buscar(nombre).count - 1) / JUEGOS_POR_PAGINA) + 1
  end

  ##
  # Permite obtener el número de páginas totales para los juegos del usuario logueado.
  #
  # * <tt>usuario</tt> - Usuario para buscar sus juegos asociados.
  
  def self.paginas_por_usuario(usuario)
    ((por_usuario(usuario).count - 1) / JUEGOS_POR_PAGINA) + 1
  end
  
  ##
  # Permite obtener la mejor puntuación.
  
  def mejor_puntuacion
    puntuaciones.order('puntos DESC').eager_load(:usuario).first
  end
  
  ##
  # Permite obtener la mejor puntuación de un usuario.
  #
  # * <tt>usuario</tt> - Usuario sobre el que se realiza la consulta.
  
  def mejor_puntuacion_usuario(usuario)
    puntuaciones.where(:usuario_id => usuario.id).order('puntos DESC').eager_load(:usuario).first
  end
  
  ##
  # Permite obtener el ranking del usuario.
  #
  # * <tt>usuario</tt> - Usuario sobre el que se realiza la consulta.
  
  def posicion(usuario)
    Puntuacion.where(
        'puntos > ?',
        Puntuacion.where(:juego_id => id, :usuario_id => usuario.id).maximum(:puntos)
      ).count + 1
  end
end

app/controllers/juegos_controller.rb
class JuegosController < ApplicationController
  
    before_filter :authenticate_usuario!

  
  ##
  # Permite obtener todos los juegos registrados en la aplicación. Los
  # juegos se muestran ordenados por popularidad y paginados.
  #
  # * <tt>pagina</tt> - Página a mostrar. Si no se incluye se mostrará la primera.
  
  def index
    
    @pagina = params.fetch(:pagina, 1).to_i
    @juegos = Juego.pagina_todos(@pagina)
    @paginas = Juego.paginas_todos
    
  end
  
  ##
  # Permite obtener todos los juegos asociados al usuario logueado.
  # Se muestran en orden alfabético y paginados.
  #
  # * <tt>pagina</tt> - Página a mostrar. Si no se incluye se mostrará la primera.
  
  def mis_juegos
    
    @pagina = params.fetch(:pagina, 1).to_i
    @juegos = Juego.pagina_por_usuario(current_usuario, @pagina)
    @paginas = Juego.paginas_por_usuario(current_usuario)
  
  end
  
  ##
  # Permite obtener todos los juegos que contienen el texto escrito.
  # Se mostrarán en orden alfabético y paginados.
  # * <tt>pagina</tt> - Página a mostrar. Si no se incluye se mostrará la primera
  # * <tt>nombre</tt> - Nombre por el que se realiza la búsqueda.
  
  def buscar
    
    @pagina = params.fetch(:pagina, 1).to_i
    @nombre = params.fetch(:nombre, '')
    @juegos = Juego.pagina_buscar(@pagina, @nombre)
    @paginas = Juego.paginas_buscar(filtro)
    render :index    
  end
end

app/controllers/servicio/juegos_controller.rb
class Servicio::JuegosController < Servicio::ServicioController
  
  def registrar
    juego = Juego.new params.permit(:nombre)
    resultado = {}
    if juego.save
      resultado[:mensaje] = "Juego guardado correctamente"
      resultado[:id] = juego.id
    else
      resultado[:mensaje] = "Juego no guardado"
    end
    resultado[:errores] = juego.errors.messages
    render json: resultado
  end
  
  def comprobar_nombre
    juego = Juego.new params.permit(:nombre)
    resultado = {}
    if juego.validate
      resultado[:mensaje] = "Se puede crear un juego con ese nombre"
    else
      resultado[:mensaje] = "No se puede crear un juego con ese nombre"
    end
    resultado[:errores] = juego.errors.messages
    render json: resultado    
  end

end

app/views/juegos/index.html.erb
<% content_for :opcion, 'juegos' %>
<% content_for :titulo do %>
	<% if @nombre.nil? %>
		Todos los juegos
	<% else %>
		Resultados de la busqueda
	<% end %>
<% end %>
<% content_for :subtitulo do %>
	<% if @nombre.nil? %>
		Este es el listado de todos los juegos registrados en esta web
	<% else %>
		Este es el listado de todos los juegos registrados en esta web que contienen &quot;<%= @nombre %>&quot;
	<% end %>
<% end %>

<ol class="breadcrumb">
  <li class="active">Juegos</li>
</ol>


<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>Juego</th>
			<th style="width: 18em" class="puntuacion">Jugadores</th>
			<th style="width: 18em" class="puntuacion">Usuario</th>
			<th style="width: 18em" class="puntuacion">Mejor puntuación</th>			
		</tr>
	</thead>
	<tbody>
		
		<% @juegos.each do |juego| %>
			<tr>
				<td><%= link_to juego.nombre, puntuaciones_juego_path(juego.id) %></td>
				<td class="puntuacion"><%= juego.jugadores %></td>
				<td class="puntuacion">
					<% puntuacion = juego.mejor_puntuacion %>
					<% if !puntuacion.nil? %>
						<%= puntuacion.usuario.nombre %>
					<% end %>
				</td>
				<td class="puntuacion">
					<% puntuacion = juego.mejor_puntuacion %>
					<% if !puntuacion.nil? %>
						<%= puntuacion.puntos %>
					<% end %>
				</td>
			</tr>
		<% end %>
		
	</tbody>
</table>

<% if @nombre.nil? %>
	<%= render :partial => 'partials/paginador', :locals => {:url => root_path + '?'} %>
<% else %>
	<%= render :partial => 'partials/paginador', :locals => {:url => buscar_path(:nombre => @nombre) + '&'} %>
<% end %>

<p align="right">Número total de juegos: <%= Juego.count %> </p>

app/views/juegos/mis_juegos.html.erb
<% content_for :opcion, 'mis_juegos' %>
<% content_for :titulo do %>
	Mis juegos
<% end %>
<% content_for :subtitulo do %>
	Este es el listado de todos los juegos a los que has jugado
<% end %>

<ol class="breadcrumb">
  <li class="active">Mis Juegos</li>
</ol>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>Juego</th>				
			<th style="width: 25em" class="puntuacion">Ranking</th>			
			<th style="width: 29em" class="puntuacion">Mi Puntuación</th>
		</tr>
	</thead>
	<tbody>
			<% @juegos.each do |juego| %>
			<tr>
				<td><%= link_to juego.nombre, puntuaciones_juego_path(juego.id) %></td>
				<td class="puntuacion">
					<%= juego.posicion(current_usuario) %>
				</td>
				
				<td class="puntuacion">
					<% puntuacion = juego.mejor_puntuacion_usuario(current_usuario) %>
					<% if !puntuacion.nil? %>
						<%= puntuacion.puntos%>
					<% end %>
				</td>
				<td class="puntuacion">				
			</tr>
		<% end %>
	</tbody>
</table>

<%= render :partial => 'partials/paginador', :locals => {:url => mis_juegos_path + '?'} %>

<p align="right">Número total de juegos: <%= Juego.por_usuario(current_usuario).count %> </p>