config/routes.rb
Rails.application.routes.draw do

  get 'puntuaciones/index'

  devise_for :usuarios, :controllers => {
    :sessions => 'usuario/sessions',
    :registrations => 'usuario/registrations',
    :passwords => 'usuario/password'
    }

  post 'registrar' => 'servicio/usuarios#registrar'
  post 'login' => 'servicio/usuarios#login'

  post 'juegos/registrar' => 'servicio/juegos#registrar'
  post 'juegos/comprobar' => 'servicio/juegos#comprobar_nombre'

  post 'puntuaciones/registrar' => 'servicio/puntuaciones#registrar'
  post 'puntuaciones/mejores' => 'servicio/puntuaciones#mejores'

  root 'inicio#inicio'
  
  get 'mis-juegos' => 'juegos#mis_juegos'
  
  get 'juegos' => 'juegos#index'
  get 'buscar' => 'juegos#buscar'
  
  get 'puntuaciones/:juego_id' => 'puntuaciones#index', :as => 'puntuaciones_juego'
  
  get 'puntuaciones/niveles/:puntuacion_id' => 'niveles#index', :as => 'puntuaciones_por_nivel'

  devise_scope :usuario do
   get "mi-cuenta", to: "devise/passwords#edit"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrivialProgramarWS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>		
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<%= link_to 'Educapp', root_path, :class => 'navbar-brand' %>
				</div>
				<ul class="nav navbar-nav">
					<% opcion = yield :opcion %>
					<li <%= opcion == 'juegos' ? 'class="active"'.html_safe : '' %>>
						<%= link_to root_path do%>
							<span class="glyphicon glyphicon-phone"></span>
							<span>Juegos</span>
						<% end %>									
					</li>
					<li <%= opcion == 'mis_juegos' ? 'class="active"'.html_safe : '' %>>
						<%= link_to mis_juegos_path do%>
						<span class="glyphicon glyphicon-star"></span>
						<span>Mis Juegos</span>
						<% end %>
					</li>							
					<li>								
	                    <div class="navbar-form " role="search">
	                    	<%= form_tag buscar_path, :method => :get do %>
		                        <div class="input-group" id="buscar">
		                        	<%= text_field_tag :nombre, @nombre, :placeholder => 'Buscar juego...', :class => 'form-control', :style => 'max-width: 100%; width: 100%;' %>
		                            <div class="input-group-btn">
		                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
		                            </div>
		                        </div>
		                    <% end %>
	                    </div>           									 
					</li>
				</ul>				
				<ul class="nav navbar-nav navbar-right">				
					<li>					
  						<%= link_to edit_usuario_registration_path do %>
  						<span class="glyphicon glyphicon-user"></span>
    					<span>Mi cuenta</span>
  						<% end %>				
					</li>
					<li>
						<%= link_to destroy_usuario_session_path, :method => :delete do %>
						<span class="glyphicon glyphicon-log-out"></span>
						<span>Cerrar Sesión</span>
						<% end %>
					</li>
				</ul>
			</div>
		</nav>
		<div id="titulo">
			<div class="container">
				<h1><%= yield :titulo %></h1>
				<p><%= yield :subtitulo %></p>
			</div>
		</div>
	</header>
	<div class="container">
		
		<% if !notice.nil? %>
			<div class="alert alert-success" role="alert">
				<%= notice %>
			</div>
		<% end %>
		<% if !alert.nil? %>
			<div class="alert alert-danger" role="alert">
				<%= alert %>
			</div>
		<% end %>
		
		<%= yield %>
	</div>

</body>
</html>

app/views/layouts/inicio.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrivialProgramarWS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="inicio">
	<div class="contenedor-border-form-div">

		<% if !notice.nil? %>
			<div class="alert alert-success" role="alert">
				<%= notice %>
			</div>
		<% end %>
		<% if !alert.nil? %>
			<div class="alert alert-danger" role="alert">
				<%= alert %>
			</div>
		<% end %>

		<div class="border-form-div">
			<%= yield %>
		</div>
	</div>
</body>
</html>